# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app/ui/export_dialog.ui'
#
# Created: Fri Mar 21 16:26:54 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(530, 280)
        self.verticalLayout = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox_only_selected = QtGui.QCheckBox(Dialog)
        self.checkBox_only_selected.setObjectName("checkBox_only_selected")
        self.verticalLayout.addWidget(self.checkBox_only_selected)
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtGui.QLabel(self.tab_2)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_csv = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_csv.setObjectName("lineEdit_csv")
        self.horizontalLayout.addWidget(self.lineEdit_csv)
        self.pushButton_csv_browse = QtGui.QPushButton(self.tab_2)
        self.pushButton_csv_browse.setObjectName("pushButton_csv_browse")
        self.horizontalLayout.addWidget(self.pushButton_csv_browse)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.pushButton_csv_export = QtGui.QPushButton(self.tab_2)
        self.pushButton_csv_export.setObjectName("pushButton_csv_export")
        self.verticalLayout_2.addWidget(self.pushButton_csv_export)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.checkBox_per_grid = QtGui.QCheckBox(self.tab)
        self.checkBox_per_grid.setObjectName("checkBox_per_grid")
        self.verticalLayout_3.addWidget(self.checkBox_per_grid)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit_dat = QtGui.QLineEdit(self.tab)
        self.lineEdit_dat.setObjectName("lineEdit_dat")
        self.horizontalLayout_2.addWidget(self.lineEdit_dat)
        self.pushButton_dat_browse = QtGui.QPushButton(self.tab)
        self.pushButton_dat_browse.setObjectName("pushButton_dat_browse")
        self.horizontalLayout_2.addWidget(self.pushButton_dat_browse)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.pushButton_dat_export = QtGui.QPushButton(self.tab)
        self.pushButton_dat_export.setObjectName("pushButton_dat_export")
        self.verticalLayout_3.addWidget(self.pushButton_dat_export)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_6 = QtGui.QLabel(self.tab_3)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.lineEdit_pial = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_pial.setObjectName("lineEdit_pial")
        self.horizontalLayout_4.addWidget(self.lineEdit_pial)
        self.pushButton_pial_browse = QtGui.QPushButton(self.tab_3)
        self.pushButton_pial_browse.setObjectName("pushButton_pial_browse")
        self.horizontalLayout_4.addWidget(self.pushButton_pial_browse)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtGui.QLabel(self.tab_3)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.lineEdit_distance = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_distance.setObjectName("lineEdit_distance")
        self.horizontalLayout_3.addWidget(self.lineEdit_distance)
        self.pushButton_distance_browse = QtGui.QPushButton(self.tab_3)
        self.pushButton_distance_browse.setObjectName("pushButton_distance_browse")
        self.horizontalLayout_3.addWidget(self.pushButton_distance_browse)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.pushButton_pial_export = QtGui.QPushButton(self.tab_3)
        self.pushButton_pial_export.setObjectName("pushButton_pial_export")
        self.verticalLayout_4.addWidget(self.pushButton_pial_export)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.tabWidget.addTab(self.tab_3, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.label_4 = QtGui.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Export Registered Electrodes...", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_only_selected.setText(QtGui.QApplication.translate("Dialog", "Only Export Selected Electrodes", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Output Path", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_csv_browse.setText(QtGui.QApplication.translate("Dialog", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_csv_export.setText(QtGui.QApplication.translate("Dialog", "Export", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("Dialog", "CSV", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_per_grid.setText(QtGui.QApplication.translate("Dialog", "Export a .dat File for Each Grid", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Output Path", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_dat_browse.setText(QtGui.QApplication.translate("Dialog", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_dat_export.setText(QtGui.QApplication.translate("Dialog", "Export", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("Dialog", "Freesurfer Pointset", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "Pial Path", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_pial_browse.setText(QtGui.QApplication.translate("Dialog", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Output Path", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_distance_browse.setText(QtGui.QApplication.translate("Dialog", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_pial_export.setText(QtGui.QApplication.translate("Dialog", "Export", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("Dialog", "Pial Distance", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Note: the output vertex indices starts from 0.", None, QtGui.QApplication.UnicodeUTF8))

