# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app/ui/mainwindow.ui'
#
# Created: Fri Apr 11 15:27:36 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 645)
        MainWindow.setStyleSheet("QMenuBar { \n"
"    background-color: rgb(197, 197, 197);\n"
"}\n"
"\n"
"QMenuBar::item {\n"
"    background-color: rgb(197, 197, 197);\n"
"    color: black;\n"
"}")
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 25))
        self.menubar.setAutoFillBackground(False)
        self.menubar.setNativeMenuBar(False)
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuAdvanced = QtGui.QMenu(self.menubar)
        self.menuAdvanced.setObjectName("menuAdvanced")
        MainWindow.setMenuBar(self.menubar)
        self.dockWidget = QtGui.QDockWidget(MainWindow)
        self.dockWidget.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        self.dockWidget.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_3.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget = QtGui.QTabWidget(self.dockWidgetContents)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_segment = QtGui.QWidget()
        self.tab_segment.setObjectName("tab_segment")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.tab_segment)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.pushButton_open_ct_dura = QtGui.QPushButton(self.tab_segment)
        self.pushButton_open_ct_dura.setAutoDefault(False)
        self.pushButton_open_ct_dura.setDefault(False)
        self.pushButton_open_ct_dura.setObjectName("pushButton_open_ct_dura")
        self.verticalLayout_7.addWidget(self.pushButton_open_ct_dura)
        self.frame_segment = QtGui.QFrame(self.tab_segment)
        self.frame_segment.setEnabled(False)
        self.frame_segment.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_segment.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_segment.setLineWidth(2)
        self.frame_segment.setObjectName("frame_segment")
        self.verticalLayout = QtGui.QVBoxLayout(self.frame_segment)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtGui.QGroupBox(self.frame_segment)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalSlider_threshold = QtGui.QSlider(self.groupBox)
        self.horizontalSlider_threshold.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_threshold.setObjectName("horizontalSlider_threshold")
        self.horizontalLayout_2.addWidget(self.horizontalSlider_threshold)
        self.spinBox_threshold = QtGui.QSpinBox(self.groupBox)
        self.spinBox_threshold.setObjectName("spinBox_threshold")
        self.horizontalLayout_2.addWidget(self.spinBox_threshold)
        self.verticalLayout.addWidget(self.groupBox)
        self.pushButton_preview_threshold = QtGui.QPushButton(self.frame_segment)
        self.pushButton_preview_threshold.setObjectName("pushButton_preview_threshold")
        self.verticalLayout.addWidget(self.pushButton_preview_threshold)
        self.pushButton_hide_preview = QtGui.QPushButton(self.frame_segment)
        self.pushButton_hide_preview.setEnabled(False)
        self.pushButton_hide_preview.setObjectName("pushButton_hide_preview")
        self.verticalLayout.addWidget(self.pushButton_hide_preview)
        self.verticalLayout_7.addWidget(self.frame_segment)
        self.frame_segment_config = QtGui.QFrame(self.tab_segment)
        self.frame_segment_config.setEnabled(False)
        self.frame_segment_config.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_segment_config.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_segment_config.setObjectName("frame_segment_config")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.frame_segment_config)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox_heuristic_distance = QtGui.QGroupBox(self.frame_segment_config)
        self.groupBox_heuristic_distance.setObjectName("groupBox_heuristic_distance")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupBox_heuristic_distance)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalSlider_distance = QtGui.QSlider(self.groupBox_heuristic_distance)
        self.horizontalSlider_distance.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_distance.setInvertedControls(False)
        self.horizontalSlider_distance.setTickPosition(QtGui.QSlider.NoTicks)
        self.horizontalSlider_distance.setObjectName("horizontalSlider_distance")
        self.horizontalLayout_3.addWidget(self.horizontalSlider_distance)
        self.doubleSpinBox_distance = QtGui.QDoubleSpinBox(self.groupBox_heuristic_distance)
        self.doubleSpinBox_distance.setObjectName("doubleSpinBox_distance")
        self.horizontalLayout_3.addWidget(self.doubleSpinBox_distance)
        self.label = QtGui.QLabel(self.groupBox_heuristic_distance)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.verticalLayout_6.addWidget(self.groupBox_heuristic_distance)
        self.groupBox_heuristic_size = QtGui.QGroupBox(self.frame_segment_config)
        self.groupBox_heuristic_size.setObjectName("groupBox_heuristic_size")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.groupBox_heuristic_size)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalSlider_size = QtGui.QSlider(self.groupBox_heuristic_size)
        self.horizontalSlider_size.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_size.setObjectName("horizontalSlider_size")
        self.horizontalLayout_4.addWidget(self.horizontalSlider_size)
        self.doubleSpinBox_size = QtGui.QDoubleSpinBox(self.groupBox_heuristic_size)
        self.doubleSpinBox_size.setObjectName("doubleSpinBox_size")
        self.horizontalLayout_4.addWidget(self.doubleSpinBox_size)
        self.label_2 = QtGui.QLabel(self.groupBox_heuristic_size)
        self.label_2.setTextFormat(QtCore.Qt.RichText)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.verticalLayout_6.addWidget(self.groupBox_heuristic_size)
        self.verticalLayout_7.addWidget(self.frame_segment_config)
        self.pushButton_segment = QtGui.QPushButton(self.tab_segment)
        self.pushButton_segment.setEnabled(False)
        self.pushButton_segment.setObjectName("pushButton_segment")
        self.verticalLayout_7.addWidget(self.pushButton_segment)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem)
        self.tabWidget.addTab(self.tab_segment, "")
        self.tab_edit = QtGui.QWidget()
        self.tab_edit.setEnabled(False)
        self.tab_edit.setObjectName("tab_edit")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab_edit)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.treeView_edit = QtGui.QTreeView(self.tab_edit)
        self.treeView_edit.setAlternatingRowColors(True)
        self.treeView_edit.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.treeView_edit.setObjectName("treeView_edit")
        self.verticalLayout_2.addWidget(self.treeView_edit)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem1)
        self.label_edit_select_count = QtGui.QLabel(self.tab_edit)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_edit_select_count.sizePolicy().hasHeightForWidth())
        self.label_edit_select_count.setSizePolicy(sizePolicy)
        self.label_edit_select_count.setObjectName("label_edit_select_count")
        self.horizontalLayout_9.addWidget(self.label_edit_select_count)
        self.label_6 = QtGui.QLabel(self.tab_edit)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_9.addWidget(self.label_6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_edit_electrode_count = QtGui.QLabel(self.tab_edit)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_edit_electrode_count.sizePolicy().hasHeightForWidth())
        self.label_edit_electrode_count.setSizePolicy(sizePolicy)
        self.label_edit_electrode_count.setText("")
        self.label_edit_electrode_count.setObjectName("label_edit_electrode_count")
        self.horizontalLayout_7.addWidget(self.label_edit_electrode_count)
        self.label_7 = QtGui.QLabel(self.tab_edit)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.label_component_count = QtGui.QLabel(self.tab_edit)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_component_count.sizePolicy().hasHeightForWidth())
        self.label_component_count.setSizePolicy(sizePolicy)
        self.label_component_count.setText("")
        self.label_component_count.setObjectName("label_component_count")
        self.horizontalLayout_7.addWidget(self.label_component_count)
        self.label_5 = QtGui.QLabel(self.tab_edit)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_7.addWidget(self.label_5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.line = QtGui.QFrame(self.tab_edit)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.pushButton_add = QtGui.QPushButton(self.tab_edit)
        self.pushButton_add.setCheckable(True)
        self.pushButton_add.setObjectName("pushButton_add")
        self.verticalLayout_2.addWidget(self.pushButton_add)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.pushButton_remove = QtGui.QPushButton(self.tab_edit)
        self.pushButton_remove.setObjectName("pushButton_remove")
        self.horizontalLayout_10.addWidget(self.pushButton_remove)
        self.pushButton_restore = QtGui.QPushButton(self.tab_edit)
        self.pushButton_restore.setObjectName("pushButton_restore")
        self.horizontalLayout_10.addWidget(self.pushButton_restore)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtGui.QLabel(self.tab_edit)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.spinBox_split = QtGui.QSpinBox(self.tab_edit)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_split.sizePolicy().hasHeightForWidth())
        self.spinBox_split.setSizePolicy(sizePolicy)
        self.spinBox_split.setMinimum(2)
        self.spinBox_split.setObjectName("spinBox_split")
        self.horizontalLayout_5.addWidget(self.spinBox_split)
        self.pushButton_split = QtGui.QPushButton(self.tab_edit)
        self.pushButton_split.setObjectName("pushButton_split")
        self.horizontalLayout_5.addWidget(self.pushButton_split)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.pushButton_clear = QtGui.QPushButton(self.tab_edit)
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.verticalLayout_2.addWidget(self.pushButton_clear)
        self.tabWidget.addTab(self.tab_edit, "")
        self.tab_label = QtGui.QWidget()
        self.tab_label.setEnabled(False)
        self.tab_label.setObjectName("tab_label")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tab_label)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tableView_label = QtGui.QTableView(self.tab_label)
        self.tableView_label.setAlternatingRowColors(True)
        self.tableView_label.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableView_label.setSortingEnabled(True)
        self.tableView_label.setObjectName("tableView_label")
        self.verticalLayout_5.addWidget(self.tableView_label)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem3)
        self.label_label_select_count = QtGui.QLabel(self.tab_label)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_label_select_count.sizePolicy().hasHeightForWidth())
        self.label_label_select_count.setSizePolicy(sizePolicy)
        self.label_label_select_count.setObjectName("label_label_select_count")
        self.horizontalLayout_12.addWidget(self.label_label_select_count)
        self.label_10 = QtGui.QLabel(self.tab_label)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_12.addWidget(self.label_10)
        self.verticalLayout_5.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.lineEdit_grid_label = QtGui.QLineEdit(self.tab_label)
        self.lineEdit_grid_label.setObjectName("lineEdit_grid_label")
        self.horizontalLayout_8.addWidget(self.lineEdit_grid_label)
        self.pushButton_assign_grid_label = QtGui.QPushButton(self.tab_label)
        self.pushButton_assign_grid_label.setObjectName("pushButton_assign_grid_label")
        self.horizontalLayout_8.addWidget(self.pushButton_assign_grid_label)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.pushButton_label_clear = QtGui.QPushButton(self.tab_label)
        self.pushButton_label_clear.setObjectName("pushButton_label_clear")
        self.verticalLayout_5.addWidget(self.pushButton_label_clear)
        self.pushButton_export = QtGui.QPushButton(self.tab_label)
        self.pushButton_export.setObjectName("pushButton_export")
        self.verticalLayout_5.addWidget(self.pushButton_export)
        self.tabWidget.addTab(self.tab_label, "")
        self.tab_register = QtGui.QWidget()
        self.tab_register.setEnabled(False)
        self.tab_register.setObjectName("tab_register")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab_register)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.listView_register = QtGui.QListView(self.tab_register)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listView_register.sizePolicy().hasHeightForWidth())
        self.listView_register.setSizePolicy(sizePolicy)
        self.listView_register.setAlternatingRowColors(True)
        self.listView_register.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.listView_register.setObjectName("listView_register")
        self.verticalLayout_4.addWidget(self.listView_register)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.label_register_select_count = QtGui.QLabel(self.tab_register)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_register_select_count.sizePolicy().hasHeightForWidth())
        self.label_register_select_count.setSizePolicy(sizePolicy)
        self.label_register_select_count.setObjectName("label_register_select_count")
        self.horizontalLayout_6.addWidget(self.label_register_select_count)
        self.label_8 = QtGui.QLabel(self.tab_register)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_register_complete_count = QtGui.QLabel(self.tab_register)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_register_complete_count.sizePolicy().hasHeightForWidth())
        self.label_register_complete_count.setSizePolicy(sizePolicy)
        self.label_register_complete_count.setObjectName("label_register_complete_count")
        self.horizontalLayout_11.addWidget(self.label_register_complete_count)
        self.label_9 = QtGui.QLabel(self.tab_register)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_11.addWidget(self.label_9)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem5)
        self.label_register_electrode_count = QtGui.QLabel(self.tab_register)
        self.label_register_electrode_count.setObjectName("label_register_electrode_count")
        self.horizontalLayout_11.addWidget(self.label_register_electrode_count)
        self.label_4 = QtGui.QLabel(self.tab_register)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_11.addWidget(self.label_4)
        self.verticalLayout_4.addLayout(self.horizontalLayout_11)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_svd = QtGui.QPushButton(self.tab_register)
        self.pushButton_svd.setObjectName("pushButton_svd")
        self.gridLayout.addWidget(self.pushButton_svd, 1, 0, 1, 1)
        self.pushButton_manual = QtGui.QPushButton(self.tab_register)
        self.pushButton_manual.setCheckable(True)
        self.pushButton_manual.setChecked(False)
        self.pushButton_manual.setObjectName("pushButton_manual")
        self.gridLayout.addWidget(self.pushButton_manual, 1, 1, 1, 1)
        self.pushButton_nearest = QtGui.QPushButton(self.tab_register)
        self.pushButton_nearest.setObjectName("pushButton_nearest")
        self.gridLayout.addWidget(self.pushButton_nearest, 0, 1, 1, 1)
        self.pushButton_principal = QtGui.QPushButton(self.tab_register)
        self.pushButton_principal.setObjectName("pushButton_principal")
        self.gridLayout.addWidget(self.pushButton_principal, 0, 0, 1, 1)
        self.pushButton_unregister = QtGui.QPushButton(self.tab_register)
        self.pushButton_unregister.setObjectName("pushButton_unregister")
        self.gridLayout.addWidget(self.pushButton_unregister, 2, 0, 1, 2)
        self.verticalLayout_4.addLayout(self.gridLayout)
        self.pushButton_register_clear = QtGui.QPushButton(self.tab_register)
        self.pushButton_register_clear.setObjectName("pushButton_register_clear")
        self.verticalLayout_4.addWidget(self.pushButton_register_clear)
        self.tabWidget.addTab(self.tab_register, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionOpenProject = QtGui.QAction(MainWindow)
        self.actionOpenProject.setObjectName("actionOpenProject")
        self.actionSaveProject = QtGui.QAction(MainWindow)
        self.actionSaveProject.setObjectName("actionSaveProject")
        self.actionRecentProjects = QtGui.QAction(MainWindow)
        self.actionRecentProjects.setObjectName("actionRecentProjects")
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionSaveProjectAs = QtGui.QAction(MainWindow)
        self.actionSaveProjectAs.setObjectName("actionSaveProjectAs")
        self.actionOpenPial = QtGui.QAction(MainWindow)
        self.actionOpenPial.setObjectName("actionOpenPial")
        self.actionShowPial = QtGui.QAction(MainWindow)
        self.actionShowPial.setCheckable(True)
        self.actionShowPial.setObjectName("actionShowPial")
        self.actionHideThresholdingPreview = QtGui.QAction(MainWindow)
        self.actionHideThresholdingPreview.setObjectName("actionHideThresholdingPreview")
        self.actionExport_segmentation_dataset = QtGui.QAction(MainWindow)
        self.actionExport_segmentation_dataset.setObjectName("actionExport_segmentation_dataset")
        self.actionShow_Electrode_ID = QtGui.QAction(MainWindow)
        self.actionShow_Electrode_ID.setCheckable(True)
        self.actionShow_Electrode_ID.setObjectName("actionShow_Electrode_ID")
        self.actionAbout_Qt = QtGui.QAction(MainWindow)
        self.actionAbout_Qt.setObjectName("actionAbout_Qt")
        self.actionReport_an_issue = QtGui.QAction(MainWindow)
        self.actionReport_an_issue.setObjectName("actionReport_an_issue")
        self.actionDocumentation = QtGui.QAction(MainWindow)
        self.actionDocumentation.setObjectName("actionDocumentation")
        self.actionSource_Repository = QtGui.QAction(MainWindow)
        self.actionSource_Repository.setObjectName("actionSource_Repository")
        self.actionLicense = QtGui.QAction(MainWindow)
        self.actionLicense.setObjectName("actionLicense")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionOpenPial)
        self.menuFile.addAction(self.actionOpenProject)
        self.menuFile.addAction(self.actionSaveProject)
        self.menuFile.addAction(self.actionSaveProjectAs)
        self.menuFile.addAction(self.actionRecentProjects)
        self.menuHelp.addAction(self.actionReport_an_issue)
        self.menuHelp.addAction(self.actionDocumentation)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionAbout_Qt)
        self.menuHelp.addAction(self.actionSource_Repository)
        self.menuHelp.addAction(self.actionLicense)
        self.menuView.addAction(self.actionShowPial)
        self.menuView.addAction(self.actionHideThresholdingPreview)
        self.menuView.addAction(self.actionShow_Electrode_ID)
        self.menuAdvanced.addAction(self.actionExport_segmentation_dataset)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuAdvanced.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.horizontalSlider_threshold, QtCore.SIGNAL("sliderMoved(int)"), self.spinBox_threshold.setValue)
        QtCore.QObject.connect(self.pushButton_open_ct_dura, QtCore.SIGNAL("clicked()"), self.actionOpen.trigger)
        QtCore.QObject.connect(self.spinBox_threshold, QtCore.SIGNAL("valueChanged(int)"), self.horizontalSlider_threshold.setValue)
        QtCore.QObject.connect(self.pushButton_hide_preview, QtCore.SIGNAL("clicked()"), self.actionHideThresholdingPreview.trigger)
        QtCore.QObject.connect(self.pushButton_clear, QtCore.SIGNAL("clicked()"), self.treeView_edit.clearSelection)
        QtCore.QObject.connect(self.pushButton_register_clear, QtCore.SIGNAL("clicked()"), self.listView_register.clearSelection)
        QtCore.QObject.connect(self.pushButton_label_clear, QtCore.SIGNAL("clicked()"), self.tableView_label.clearSelection)
        QtCore.QObject.connect(self.lineEdit_grid_label, QtCore.SIGNAL("returnPressed()"), self.pushButton_assign_grid_label.click)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Interactive Electrode Registration", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuView.setTitle(QtGui.QApplication.translate("MainWindow", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAdvanced.setTitle(QtGui.QApplication.translate("MainWindow", "Advanced", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_open_ct_dura.setText(QtGui.QApplication.translate("MainWindow", "Open CT and Dura...", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setToolTip(QtGui.QApplication.translate("MainWindow", "lower bound on a connected component\'s CT intensity", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Threshold", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_preview_threshold.setText(QtGui.QApplication.translate("MainWindow", "Preview Thresholding", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_hide_preview.setText(QtGui.QApplication.translate("MainWindow", "Hide Preview", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_heuristic_distance.setToolTip(QtGui.QApplication.translate("MainWindow", "upper bound on a connected component\'s distance to dura", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_heuristic_distance.setTitle(QtGui.QApplication.translate("MainWindow", "Distance", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "mm", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_heuristic_size.setToolTip(QtGui.QApplication.translate("MainWindow", "lower bound on a connected component\'s size", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_heuristic_size.setTitle(QtGui.QApplication.translate("MainWindow", "Size", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "mm<sup>3</sup>", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_segment.setText(QtGui.QApplication.translate("MainWindow", "Segment", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_segment), QtGui.QApplication.translate("MainWindow", "Segment", None, QtGui.QApplication.UnicodeUTF8))
        self.label_edit_select_count.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Selected", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Electrodes ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Components", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_add.setText(QtGui.QApplication.translate("MainWindow", "&Add", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_add.setShortcut(QtGui.QApplication.translate("MainWindow", "A", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_remove.setText(QtGui.QApplication.translate("MainWindow", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_remove.setShortcut(QtGui.QApplication.translate("MainWindow", "Del", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_restore.setText(QtGui.QApplication.translate("MainWindow", "Restore", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_restore.setShortcut(QtGui.QApplication.translate("MainWindow", "Shift+Del", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Pieces", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_split.setText(QtGui.QApplication.translate("MainWindow", "&Split", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_split.setShortcut(QtGui.QApplication.translate("MainWindow", "S", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_clear.setText(QtGui.QApplication.translate("MainWindow", "&Clear Selection", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_clear.setShortcut(QtGui.QApplication.translate("MainWindow", "C", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_edit), QtGui.QApplication.translate("MainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.label_label_select_count.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Selected", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_assign_grid_label.setText(QtGui.QApplication.translate("MainWindow", "&Assign Grid Label", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_assign_grid_label.setShortcut(QtGui.QApplication.translate("MainWindow", "A", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_label_clear.setText(QtGui.QApplication.translate("MainWindow", "&Clear Selection", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_label_clear.setShortcut(QtGui.QApplication.translate("MainWindow", "C", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_export.setText(QtGui.QApplication.translate("MainWindow", "&Export...", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_export.setShortcut(QtGui.QApplication.translate("MainWindow", "E", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_label), QtGui.QApplication.translate("MainWindow", "Label", None, QtGui.QApplication.UnicodeUTF8))
        self.label_register_select_count.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Selected", None, QtGui.QApplication.UnicodeUTF8))
        self.label_register_complete_count.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Registered", None, QtGui.QApplication.UnicodeUTF8))
        self.label_register_electrode_count.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Electrodes", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_svd.setText(QtGui.QApplication.translate("MainWindow", "&Best-fit Plane", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_svd.setShortcut(QtGui.QApplication.translate("MainWindow", "B", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_manual.setToolTip(QtGui.QApplication.translate("MainWindow", "right click to register; only supports single selection", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_manual.setText(QtGui.QApplication.translate("MainWindow", "&Manual", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_manual.setShortcut(QtGui.QApplication.translate("MainWindow", "M", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_nearest.setText(QtGui.QApplication.translate("MainWindow", "&Nearest Vertex", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_nearest.setShortcut(QtGui.QApplication.translate("MainWindow", "N", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_principal.setText(QtGui.QApplication.translate("MainWindow", "&Principal Axis", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_principal.setShortcut(QtGui.QApplication.translate("MainWindow", "P", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_unregister.setText(QtGui.QApplication.translate("MainWindow", "&Unregister", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_unregister.setShortcut(QtGui.QApplication.translate("MainWindow", "U", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_register_clear.setText(QtGui.QApplication.translate("MainWindow", "&Clear Selection", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_register_clear.setShortcut(QtGui.QApplication.translate("MainWindow", "C", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_register), QtGui.QApplication.translate("MainWindow", "Register", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "Open CT/dura...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpenProject.setText(QtGui.QApplication.translate("MainWindow", "Open Project...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveProject.setText(QtGui.QApplication.translate("MainWindow", "Save Project", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveProject.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRecentProjects.setText(QtGui.QApplication.translate("MainWindow", "Recent Projects", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveProjectAs.setText(QtGui.QApplication.translate("MainWindow", "Save Project As...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpenPial.setText(QtGui.QApplication.translate("MainWindow", "Open Pial...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShowPial.setText(QtGui.QApplication.translate("MainWindow", "Show Pial", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHideThresholdingPreview.setText(QtGui.QApplication.translate("MainWindow", "Hide Thresholding Preview", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExport_segmentation_dataset.setText(QtGui.QApplication.translate("MainWindow", "Export Segmentation Dataset", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShow_Electrode_ID.setText(QtGui.QApplication.translate("MainWindow", "Show Electrode ID", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout_Qt.setText(QtGui.QApplication.translate("MainWindow", "About Qt", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReport_an_issue.setText(QtGui.QApplication.translate("MainWindow", "Report an Issue...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDocumentation.setText(QtGui.QApplication.translate("MainWindow", "Documentation", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSource_Repository.setText(QtGui.QApplication.translate("MainWindow", "Source Repository", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLicense.setText(QtGui.QApplication.translate("MainWindow", "License", None, QtGui.QApplication.UnicodeUTF8))

